### ISSUE TITLE
Alfresco Share 7.1 shows some english text when browser locale is Brazilian Portuguese

### ISSUE THREAD

**Issue by iohann95** [Alfresco/alfresco-community-share#1]
In Alfresco Share 7.1 version, some parts of Share always shows texts in english, even when the browser locale is Brazillian Portuguese:

![7 1](https://user-images.githubusercontent.com/63069860/150205613-79891c5e-90a0-403f-93eb-c1fe7af50974.png)
![7 1_](https://user-images.githubusercontent.com/63069860/150205625-093b986e-4932-4af3-b828-3921c14141ad.png)

Using 6.2 it works just fine, it never happened:

![6 2](https://user-images.githubusercontent.com/63069860/150205641-4863a80b-72c5-4435-8020-6b7f8a94e675.png)

For the record, i'm using Angel's docker installer: https://github.com/Alfresco/alfresco-docker-installer/

I couldn't figure out what's going on... I'm assuming it's a bug in Share. Thanks!

**Comment by iohann95** [comment]
In case anyone else is having this problem, just configure Java locale and that will solve the problem...


```
-Duser.country=BR
-Duser.region=BR
-Duser.language=pt
-Duser.timezone=America/Sao_Paulo

```

**Comment by filipeaugustosantos** [comment]
> In case anyone else is having this problem, just configure Java locale and that will solve the problem...
> 
> ```
> -Duser.country=BR
> -Duser.region=BR
> -Duser.language=pt
> -Duser.timezone=America/Sao_Paulo
> ```

The indicated solution works, after inserting in alfresco and share conatainers.
however the display will always be in the informed language, and it changes the date patterns.
Any hope for a fix?
I tested it in version 7.3.0-M2, and it has the same error.
